### ISSUE TITLE
user account needed

### ISSUE THREAD

**Issue by franzmoro** [FAC7/webrtc#1]
amongst other things, this will also allow to distinguish between mentors and mentees.

**Comment by bengesoff** [comment]
do you want to allow an anonymous login option? In case the mentee needs help urgently

**Comment by aislinndb** [comment]
No need for anonymous login but profiles should be relatively anonymous e.g. mentor can only see first name and issues they want to address.
There are lots of anonymous platforms for young people that offer help in crisis - mentoring platform is about building trusting relationships so some familiarity will be needed
