### ISSUE TITLE
Project Name

### ISSUE THREAD

**Issue by andrewMacmurray** [FAC7/webrtc#19]
What should we call the app?

Couple of random ideas I had were:

'Safe Haven' (a safe place to talk)
'Roost' (a nest or a meeting place for people to feel at home / connect)

**Comment by aislinndb** [comment]
Those are both great ideas. I especially like Roost.

"Real Confidant" (play on words for 'real confident' and reinforcing the virtual/RL aspect)?

**Comment by aislinndb** [comment]
p.o.s.s.e. - acronym for 'place of safe supportive expertise'?

**Comment by andrewMacmurray** [comment]
@aislinndb nice, how about just 'confidant' - maybe nicer to restrict it to just one pun :laughing: 
- 'a person with whom one shares a secret or private matter, trusting them not to repeat it to others'

**Comment by sofer** [comment]
@aislinndb @andrewMacmurray :+1: for _"Confidant"_

**Comment by franzmoro** [comment]
can we close this issue then?
